services:
  - percona:5.6.26
  - selenium/standalone-chrome:3.12

variables:
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: prestashop
  PS_DEV_MODE: 0
  DB_SERVER: percona
  DB_NAME: prestashop
  PS_INSTALL_AUTO: 1
  PS_ERASE_DB: 1
  PS_LANGUAGE: nl
  PS_COUNTRY: nl
  PS_FOLDER_ADMIN: admin-dev
  PS_FOLDER_INSTALL: install-dev
  ADMIN_MAIL: admin@example.com
  ADMIN_PASSWD: password

stages:
  - test
  - release

test:web16:
  image: prestashop/prestashop:1.6
  before_script:
  - sed -i "s/exec apache2-foreground/service apache2 start/g" /tmp/docker_run.sh
  - sed -i 's/^error_reporting = .*/error_reporting = E_ALL \& ~E_NOTICE \& ~E_STRICT \& ~E_DEPRECATED/g' /usr/local/etc/php/php.ini
  - apt-get update && apt-get install -y git
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
  - export SITE_HOST=$(getent hosts $HOSTNAME | awk '{ print $1 }')
  script:
  - /tmp/docker_run.sh
  - composer install
  - ln -s $PWD /var/www/html/modules/bolplaza
  - ./libraries/bin/phpunit --debug --exclude-group=17
  artifacts:
    when: on_failure
    paths:
      - results/*
    expire_in: 1 week


test:web17:
  image: prestashop/prestashop:1.7-7.0
  before_script:
  - sed -i "s/exec apache2-foreground/service apache2 start/g" /tmp/docker_run.sh
  - sed -i 's/^error_reporting = .*/error_reporting = E_ALL \& ~E_NOTICE \& ~E_STRICT \& ~E_DEPRECATED/g' /usr/local/etc/php/php.ini
  - apt-get update && apt-get install -y git
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
  - export SITE_HOST=$(getent hosts $HOSTNAME | awk '{ print $1 }')
  script:
  - /tmp/docker_run.sh
  - composer install
  - ln -s $PWD /var/www/html/modules/bolplaza
  - ./libraries/bin/phpunit --exclude-group=16
  artifacts:
    when: on_failure
    paths:
      - results/*
    expire_in: 1 week

package:
  image: mwienk/gitlab-ci-magento2
  stage: release
  script:
  - composer install --no-dev
  - echo $CI_COMMIT_SHA > VERSION
  - rm -rf .git* results tests
  - mkdir ../bolplaza
  - mv * ../bolplaza
  - mv ../bolplaza .
  artifacts:
    expire_in: 2 weeks
    name: "bolplaza-$CI_COMMIT_REF_SLUG-$CI_JOB_ID"
    paths:
    - .
