stages:
- build

build:
  image: mwienk/docker-bolt-builder
  stage: build
  script:
     - composer install --no-dev
     - rm -rf .git
     - rm -rf .gitignore
     - mkdir bolplaza
     - mv * bolplaza/
  artifacts:
    paths:
      - .