stages:
- build

build:
  image: mwienk/docker-bolt-builder
  stage: build
  script:
  - composer install --no-dev
  - echo $CI_COMMIT_SHA > VERSION
  - rm -rf .git*
  - mkdir ../bolplaza
  - mv * ../bolplaza
  - mv ../bolplaza .
  artifacts:
    name:
      - "bolplaza-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    paths:
      - .
    expire_in: 2 weeks