stages:
- build

build:
  image: mwienk/docker-bolt-builder
  stage: build
  script:
  - composer install --no-dev
  - echo $CI_COMMIT_SHA > VERSION
  - rm -rf .git*
  - mkdir ../bolplaza
  - mv * ../bolplaza
  - mv ../bolplaza .
  artifacts:
    expire_in: 2 weeks
    name: "bolplaza-$CI_COMMIT_REF_SLUG-$CI_JOB_ID"
    paths:
    - .
